image: mcr.microsoft.com/playwright:v1.41.1-jammy

pipelines:
  default:
    - step:
        name: Groove Packer

        script:
          - npm install
          - npx playwright install-deps
          - npm run tests:all --headless

        artifacts:
          - playwright-report/**
